name: Deploy
on:
  push:
    branches: -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fabio-github-actions"
          heroku_email: "fwchoi@edu.uwaterloo.ca"
